### PR TITLE
Replace setup.py with setup.cfg file

### PR DESCRIPTION
**Pull request by Luni-4**
This PR replaces `setup.py` file with the more declarative `setup.cfg` file.

### CODE REVIEW

**Review by rr- — COMMENTED** [review]
Thank you, I prefer the new format sooo much more, like honestly. Hoping one day for it to get integrated with `pyproject.toml`. Two questions though:

1. Is it really safe to remove `setup.py` altogether? In most of the other packages I maintain we have the following stub:

    ```python3
    """Setup routine."""
    import setuptools

    setuptools.setup()
    ```

    But I'm not really sure if it's necessary.

2. Are we sure `options.package_data` is working well in the current form?

**Comment by Luni-4** [comment]
>     1. Is it really safe to remove `setup.py` altogether? In most of the other packages I maintain we have the following stub:
>        ```python
>        """Setup routine."""
>        import setuptools
>        
>        setuptools.setup()
>        ```

Since CI passes and one of the main goal of `setup.cfg` consists of replacing the `setup.py` script, I think we can remove it. I propose to re-add it later if there are complains or problems.      

>     2. Are we sure `options.package_data` is working well in the current form?

Looking at the [documentation](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#id5) `data_files` is deprecated and we should put everything inside the [package_data](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) section

**Comment by rr-** [comment]
>We could try to package bubblesub and see if it works

Yeah, I'd appreciate that

**Comment by Luni-4** [comment]
We need `setup.py` to run:
`python setup.py sdist` and `python setup.py bdist_wheel`

Updated

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
Thanks!

**Pull request merged**
